/* The DSH shell owns colour, state, and interaction tokens.  These few
   editor variables only describe the writing surface. */
export const redesignedStyles = `
.shell{
  --editor-paper-bg:var(--dsw-alias-bg-base,Canvas);
  --editor-paper-ink:var(--dsw-alias-text-primary,CanvasText);
  --editor-paper-muted:var(--dsw-alias-text-secondary,GrayText);
  --editor-paper-line:color-mix(in srgb,var(--dsw-alias-border-l1,CanvasText) 72%,transparent);
  --editor-paper-inset:color-mix(in srgb,var(--dsw-alias-bg-base,Canvas) 92%,var(--dsw-alias-text-primary,CanvasText));
  box-sizing:border-box;
  width:100%;height:100dvh;min-width:0;min-height:0;
  display:grid;grid-template-columns:248px minmax(0,1fr) 384px;grid-template-rows:52px minmax(0,1fr);
  overflow:hidden;background:var(--dsw-alias-bg-base,Canvas);color:var(--dsw-alias-text-primary,CanvasText);
  font:13px/1.45 var(--font-sans,system-ui,sans-serif);
}
body[data-ds-dark-theme] .shell{
  --editor-paper-bg:color-mix(in srgb,var(--dsw-alias-bg-base,Canvas) 94%,#fff);
  --editor-paper-inset:color-mix(in srgb,var(--dsw-alias-bg-base,Canvas) 82%,#000);
}
.shell *, .shell *::before,.shell *::after{box-sizing:border-box}
.shell button,.shell input,.shell select,.shell textarea{font:inherit}
.shell button{color:inherit}
.shell button:focus-visible,.shell summary:focus-visible,.shell input:focus-visible,.shell select:focus-visible,.shell textarea:focus-visible{
  outline:2px solid var(--dsw-alias-interactive-primary,Highlight);outline-offset:2px
}
.shell button:disabled{cursor:not-allowed;opacity:.52}
.sr-only{position:absolute;width:1px;height:1px;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap}
.chrome{grid-column:1/-1;display:flex;align-items:center;gap:10px;min-width:0;padding:0 16px;border-bottom:1px solid var(--dsw-alias-border-l1,ButtonBorder);background:var(--dsw-alias-bg-base,Canvas)}
.brand-lockup{display:flex;align-items:center;gap:8px;flex:none;font-size:15px;letter-spacing:-.02em}
.brand-mark{display:grid;width:24px;height:24px;place-items:center;border-radius:6px;background:var(--dsw-alias-interactive-primary,Highlight);color:var(--dsw-alias-text-on-primary,#fff);font-weight:700}
.local-state,.muted{color:var(--editor-paper-muted)}
.native-settings-control{margin-left:auto;display:flex;align-items:center}.native-settings-control button{white-space:nowrap}
.workspace-chrome{display:flex;align-items:center;gap:2px;min-width:0;max-width:min(420px,60vw);padding:2px;border:1px solid var(--dsw-alias-border-l1,ButtonBorder);border-radius:6px}.workspace-chrome .project-switcher,.workspace-chrome .workspace-menu{position:relative;min-width:0;flex:none}.workspace-chrome .project-switcher{max-width:280px}.workspace-chrome summary{display:flex;align-items:center;gap:6px;min-height:26px;max-width:100%;padding:5px 8px;border:0;border-radius:4px;background:transparent;cursor:pointer;list-style:none;font-weight:600}.workspace-chrome .project-switcher summary>span{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.workspace-chrome summary::-webkit-details-marker{display:none}.workspace-chrome summary::after{content:'⌄';flex:none;font-size:12px;color:var(--editor-paper-muted)}.workspace-chrome details[open] summary,.workspace-chrome summary:hover{background:var(--dsw-alias-bg-l1,ButtonFace)}
.workspace-menu-panel{position:absolute;z-index:10;top:calc(100% + 6px);left:0;width:224px;max-height:min(360px,70dvh);overflow:auto;padding:6px;border:1px solid var(--dsw-alias-border-l1,ButtonBorder);border-radius:7px;background:var(--dsw-alias-bg-base,Canvas);box-shadow:0 12px 28px color-mix(in srgb,var(--dsw-alias-text-primary,CanvasText) 15%,transparent)}
.workspace-menu-actions{display:grid;gap:2px}.workspace-menu-actions button{width:100%;padding:8px 9px;border:0;border-radius:4px;background:transparent;text-align:left;cursor:pointer}.workspace-menu-actions button:hover{background:var(--dsw-alias-bg-l1,ButtonFace)}.workspace-menu-actions button[aria-current=true]{color:var(--dsw-alias-interactive-primary,Highlight);font-weight:600}
.file-context-menu{position:fixed;z-index:30;min-width:168px;padding:6px;border:1px solid var(--dsw-alias-border-l1,ButtonBorder);border-radius:7px;background:var(--dsw-alias-bg-base,Canvas);box-shadow:0 12px 28px color-mix(in srgb,var(--dsw-alias-text-primary,CanvasText) 15%,transparent)}.file-context-menu button{width:100%;padding:8px 9px;border:0;border-radius:4px;background:transparent;text-align:left;cursor:pointer}.file-context-menu button:hover,.file-context-menu button:focus-visible{background:var(--dsw-alias-bg-l1,ButtonFace)}
.path-fallback{display:grid;gap:7px;margin:7px 2px 2px;padding:8px 2px 0;border-top:1px solid var(--dsw-alias-border-l1,ButtonBorder)}.path-fallback label{display:grid;gap:4px;font-size:12px;color:var(--editor-paper-muted)}.path-fallback input{min-width:0;padding:7px;border:1px solid var(--dsw-alias-border-l1,ButtonBorder);border-radius:4px;background:var(--editor-paper-bg);color:inherit}.path-fallback>div{display:flex;gap:6px}.path-fallback button{padding:6px 8px}
.layout-controls{display:flex;align-items:center;gap:2px;margin-left:auto;padding:2px;border:1px solid var(--dsw-alias-border-l1,ButtonBorder);border-radius:6px}.layout-controls button{padding:5px 8px;border:0;border-radius:4px;background:transparent;cursor:pointer}.layout-controls button:hover,.layout-controls button[aria-pressed=true]{background:var(--dsw-alias-bg-l1,ButtonFace)}.layout-controls button[aria-pressed=true]{color:var(--dsw-alias-interactive-primary,Highlight);font-weight:600}
.topbar-actions{display:flex;align-items:center;gap:8px;min-width:0}.topbar-actions>span{max-width:180px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--editor-paper-muted)}.icon-button{display:grid;place-items:center;min-width:28px;min-height:28px;padding:3px;border:0;border-radius:4px;background:transparent;cursor:pointer}.icon-button:hover{background:var(--dsw-alias-bg-l1,ButtonFace)}
.sidebar{grid-row:2;min-width:0;min-height:0;display:flex;flex-direction:column;border-right:1px solid var(--dsw-alias-border-l1,ButtonBorder);background:var(--dsw-specific-sidebar-fill,var(--dsw-alias-bg-l1,Canvas))}.side-title{display:flex;align-items:center;justify-content:space-between;padding:11px 12px 8px;font-weight:600}.side-title .icon-button{font-size:18px}
.project-actions,.archive-panel{margin:0 8px;border-top:1px solid var(--dsw-alias-border-l1,ButtonBorder)}.project-actions summary,.archive-panel summary{display:flex;align-items:center;justify-content:space-between;padding:9px 4px;cursor:pointer;color:var(--editor-paper-muted);font-size:12px}.project-actions>div{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:4px;padding:0 0 8px}.project-actions button{padding:6px 5px;border:1px solid var(--dsw-alias-border-l1,ButtonBorder);border-radius:4px;background:var(--editor-paper-bg);cursor:pointer}.project-actions button:hover{background:var(--dsw-alias-bg-l1,ButtonFace)}
.search-panel{padding:0 8px 8px}.search-panel form{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:5px}.search-panel input,.search-panel select{min-width:0;padding:7px;border:1px solid var(--dsw-alias-border-l1,ButtonBorder);border-radius:4px;background:var(--editor-paper-bg);color:inherit}.search-panel select{grid-column:1/-1;padding:4px 6px;font-size:12px}.search-panel button{padding:6px 8px;border:1px solid var(--dsw-alias-border-l1,ButtonBorder);border-radius:4px;background:var(--editor-paper-bg);cursor:pointer}.search-summary,.search-panel>.muted{margin:7px 0 0;font-size:12px}.search-results{display:grid;gap:4px;margin:7px 0 0;padding:0;list-style:none}.search-results button{width:100%;display:grid;gap:2px;text-align:left}.search-results span{overflow:hidden;color:var(--editor-paper-muted);font-size:11px;text-overflow:ellipsis;white-space:nowrap}
.tree{flex:1 1 auto;min-height:72px;overflow:auto;padding:3px 4px 8px}.tree-directory-row,.tree-file-row{display:flex;align-items:center;gap:2px}.tree-row{display:flex;align-items:center;gap:4px;min-width:0;width:100%;padding:6px 8px;border:0;border-radius:4px;background:transparent;text-align:left;cursor:pointer}.tree-row span:last-child{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.tree-row:hover{background:var(--dsw-alias-bg-l1,ButtonFace)}.tree-row[aria-current=page]{background:var(--dsw-alias-interactive-primary,Highlight);color:var(--dsw-alias-text-on-primary,#fff)}.tree-marker{width:12px;flex:none;color:var(--editor-paper-muted);text-align:center}.tree-row[aria-current=page] .tree-marker{color:inherit}.tree-directory-add{width:23px;height:23px;flex:none;border:0;border-radius:4px;background:transparent;cursor:pointer;opacity:.68}.tree-directory-row:hover .tree-directory-add,.tree-directory-add:focus-visible{opacity:1;background:var(--dsw-alias-bg-l1,ButtonFace)}
.archive-panel{margin-top:auto}.archive-panel summary small{display:grid;min-width:18px;height:18px;place-items:center;border-radius:9px;background:var(--dsw-alias-bg-l1,ButtonFace)}.archive-list{display:grid;gap:7px;max-height:190px;overflow:auto;padding:0 2px 8px}.archive-list article{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:6px;padding:7px;border:1px solid var(--dsw-alias-border-l1,ButtonBorder);border-radius:4px;background:var(--editor-paper-bg)}.archive-list strong,.archive-list small,.archive-list code{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.archive-list small,.archive-list code{color:var(--editor-paper-muted);font-size:11px}.archive-list button{align-self:start;padding:5px 6px;border:1px solid var(--dsw-alias-border-l1,ButtonBorder);border-radius:4px;background:transparent;cursor:pointer}.index-status{display:flex;align-items:center;justify-content:space-between;gap:7px;padding:8px 10px;border-top:1px solid var(--dsw-alias-border-l1,ButtonBorder);color:var(--editor-paper-muted);font-size:12px}.index-status button{flex:none;padding:4px 6px;border:0;background:transparent;color:var(--dsw-alias-interactive-primary,Highlight);cursor:pointer}
.panel-resizer{grid-row:2;position:relative;z-index:4;cursor:col-resize;background:var(--dsw-alias-border-l1,ButtonBorder)}.panel-resizer span{position:absolute;inset:0}.panel-resizer:hover,.panel-resizer:focus-visible{background:var(--dsw-alias-interactive-primary,Highlight)}
.editor{grid-row:2;min-width:0;min-height:0;display:grid;grid-template-rows:auto minmax(0,1fr) auto;background:var(--editor-paper-inset)}.editor-header{display:flex;align-items:center;gap:10px;min-width:0;padding:9px max(20px,4vw);border-bottom:1px solid var(--editor-paper-line);background:var(--editor-paper-bg);color:var(--editor-paper-muted);font-size:12px}.editor-header>span:first-child{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.editor-header>span:last-child{margin-left:auto;white-space:nowrap}.chapter-navigation{display:flex;align-items:center;gap:4px;margin-left:auto;white-space:nowrap}.chapter-navigation button{width:25px;height:24px;border:1px solid var(--dsw-alias-border-l1,ButtonBorder);border-radius:4px;background:transparent;cursor:pointer}.chapter-status-control select{padding:4px 6px;border:1px solid var(--dsw-alias-border-l1,ButtonBorder);border-radius:4px;background:var(--editor-paper-bg);color:inherit}
.paper-input{width:min(100%,920px);height:100%;justify-self:center;min-height:0;padding:42px clamp(28px,7vw,96px);border:0;resize:none;background:var(--editor-paper-bg);box-shadow:0 0 0 1px var(--editor-paper-line);color:var(--editor-paper-ink);caret-color:var(--dsw-alias-interactive-primary,Highlight);font:17px/1.95 var(--font-serif,var(--font-sans,serif));letter-spacing:.01em;outline:0}.paper-input:focus{box-shadow:0 0 0 2px color-mix(in srgb,var(--dsw-alias-interactive-primary,Highlight) 58%,transparent)}
.editor-tools{display:flex;align-items:center;gap:7px;min-height:43px;padding:7px max(16px,4vw);border-top:1px solid var(--editor-paper-line);background:var(--editor-paper-bg)}.editor-tools button,.primary-action,.composer button,.proposal button,.pending-card button,.file-dialog button,.import-dialog button,.shortcut-dialog button{padding:6px 9px;border:1px solid var(--dsw-alias-border-l1,ButtonBorder);border-radius:4px;background:transparent;cursor:pointer}.primary-action,.editor-tools button:first-child{border-color:var(--dsw-alias-interactive-primary,Highlight);background:var(--dsw-alias-interactive-primary,Highlight);color:var(--dsw-alias-text-on-primary,#fff)}.editor-tools>span{margin-left:auto;max-width:48%;overflow:hidden;color:var(--editor-paper-muted);text-overflow:ellipsis;white-space:nowrap}
.empty-paper{grid-row:2;display:grid;place-items:center;min-width:0;min-height:0;padding:32px;background:var(--editor-paper-inset);text-align:center}.empty-paper:not(.home-stage) .home-card{max-width:520px;padding:40px;border:1px solid var(--editor-paper-line);background:var(--editor-paper-bg)}.home-card h1{margin:0 0 12px;font-size:34px;letter-spacing:-.04em}.home-eyebrow{margin:0 0 8px;color:var(--editor-paper-muted);font-size:11px;font-weight:600;letter-spacing:.14em}.home-hint{max-width:37em;margin:0 auto 22px;color:var(--editor-paper-muted);line-height:1.7}.home-actions{display:flex;justify-content:center;gap:8px}.home-actions button{padding:8px 12px;border:1px solid var(--dsw-alias-border-l1,ButtonBorder);border-radius:5px;background:var(--editor-paper-bg);cursor:pointer}.home-actions .primary-action{background:var(--dsw-alias-interactive-primary,Highlight);color:var(--dsw-alias-text-on-primary,#fff)}
.ghost,.proposal{position:absolute;z-index:2;right:24px;bottom:56px;width:min(390px,46%);padding:12px;border:1px solid var(--dsw-alias-border-l1,ButtonBorder);border-radius:6px;background:var(--editor-paper-bg);box-shadow:0 14px 32px color-mix(in srgb,var(--dsw-alias-text-primary,CanvasText) 16%,transparent)}.ghost{left:24px;right:auto}.ghost p,.proposal p{white-space:pre-wrap}.ghost>div,.proposal-actions{display:flex;gap:6px;flex-wrap:wrap}.selection-diff{display:grid;gap:7px}.selection-diff section{padding:7px;background:var(--dsw-alias-bg-l1,ButtonFace)}
.chat{grid-row:2;min-width:0;min-height:0;display:grid;grid-template-rows:auto minmax(0,1fr) auto;border-left:1px solid var(--dsw-alias-border-l1,ButtonBorder);background:var(--dsw-specific-sidebar-fill,var(--dsw-alias-bg-l1,Canvas))}.chat[hidden]{display:none!important}.chat-header{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:6px;padding:10px;border-bottom:1px solid var(--dsw-alias-border-l1,ButtonBorder)}.chat-brand{display:flex;align-items:center;gap:6px}.whale-mark{width:18px;height:18px;color:var(--dsw-alias-interactive-primary,Highlight)}.conversation-select{min-width:0}.conversation-select select{width:100%;min-width:0;border:0;background:transparent;color:var(--editor-paper-muted);font-size:12px}.chat-controls{min-width:0}.compact-control{display:grid;gap:3px}.model-indicator{display:block;overflow:hidden;color:var(--editor-paper-muted);font-size:11px;text-overflow:ellipsis;white-space:nowrap}.chat-header-actions{display:flex;grid-column:2;grid-row:1;gap:2px}.chat-history{display:flex;flex-direction:column;gap:8px;min-height:0;overflow:auto;padding:12px}.chat-row,.pending-card,.proposal-card,.chat-guide{margin:0;padding:10px;border:1px solid var(--dsw-alias-border-l1,ButtonBorder);border-radius:6px;background:var(--editor-paper-bg)}.chat-row p,.pending-card p{margin:0;white-space:pre-wrap;line-height:1.65}.chat-row.user{margin-left:20px;background:color-mix(in srgb,var(--dsw-alias-interactive-primary,Highlight) 10%,var(--editor-paper-bg))}.chat-row.tool,.chat-row.notice,.chat-row.unknown{color:var(--editor-paper-muted);font-size:12px}.chat-guide{display:grid;gap:9px}.chat-guide-examples{display:grid;gap:4px}.chat-guide-examples button{padding:7px;border:1px solid var(--dsw-alias-border-l1,ButtonBorder);border-radius:4px;background:transparent;text-align:left;cursor:pointer}.pending-card{display:grid;gap:8px}.pending-card fieldset{display:grid;gap:5px;margin:0;padding:0;border:0}.pending-card input{width:100%;padding:6px;border:1px solid var(--dsw-alias-border-l1,ButtonBorder);border-radius:4px;background:var(--editor-paper-bg);color:inherit}.composer{padding:10px;border-top:1px solid var(--dsw-alias-border-l1,ButtonBorder)}.composer textarea{width:100%;min-height:78px;padding:8px;border:1px solid var(--dsw-alias-border-l1,ButtonBorder);border-radius:5px;background:var(--editor-paper-bg);color:inherit;resize:vertical}.composer>div{display:flex;justify-content:flex-end;gap:6px;padding-top:6px}.assistant-launcher{position:absolute;right:18px;bottom:16px;display:flex;align-items:center;gap:6px;padding:8px 10px;border:1px solid var(--dsw-alias-border-l1,ButtonBorder);border-radius:5px;background:var(--editor-paper-bg);box-shadow:0 8px 22px color-mix(in srgb,var(--dsw-alias-text-primary,CanvasText) 12%,transparent);cursor:pointer}
.file-dialog-overlay,.import-overlay,.shortcut-overlay{position:fixed;z-index:20;inset:0;display:grid;place-items:center;padding:24px;background:color-mix(in srgb,#000 36%,transparent)}.file-dialog,.import-dialog,.shortcut-dialog{width:min(520px,100%);max-height:min(680px,calc(100dvh - 48px));overflow:auto;padding:18px;border:1px solid var(--dsw-alias-border-l1,ButtonBorder);border-radius:8px;background:var(--editor-paper-bg);box-shadow:0 20px 60px color-mix(in srgb,#000 30%,transparent)}.file-dialog header,.import-dialog header,.shortcut-dialog header{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;margin-bottom:14px}.file-dialog h2,.import-dialog h2,.shortcut-dialog h2{margin:0;font-size:20px}.file-dialog form,.file-dialog label{display:grid;gap:7px}.file-dialog input,.file-dialog select,.import-dialog input{padding:8px;border:1px solid var(--dsw-alias-border-l1,ButtonBorder);border-radius:4px;background:var(--editor-paper-bg);color:inherit}.file-dialog footer,.import-dialog footer,.shortcut-dialog footer{display:flex;justify-content:flex-end;gap:7px;flex-wrap:wrap;margin-top:16px}.file-dialog-actions{display:grid;gap:6px}.file-dialog-actions button{text-align:left}.danger-action{border-color:var(--dsw-alias-state-error,FireBrick)!important;color:var(--dsw-alias-state-error,FireBrick)!important}.danger-link{margin-right:auto;color:var(--dsw-alias-state-error,FireBrick)!important}.archive-confirm{display:grid;gap:10px}.workspace-dialog code{display:block;overflow:auto;color:var(--editor-paper-muted);font-size:11px}.shortcut-dialog dl{display:grid;grid-template-columns:auto minmax(0,1fr);gap:8px;margin:0}.shortcut-dialog dt{font-family:ui-monospace,Consolas,monospace}.shortcut-dialog dd{margin:0;color:var(--editor-paper-muted)}
.worldbook-settings{display:grid;gap:9px;max-height:230px;overflow:auto;padding:13px max(20px,4vw);border-bottom:1px solid var(--editor-paper-line);background:var(--editor-paper-bg)}.worldbook-settings header{display:flex;align-items:center;justify-content:space-between;gap:10px}.worldbook-settings textarea,.worldbook-settings input{padding:7px;border:1px solid var(--dsw-alias-border-l1,ButtonBorder);border-radius:4px;background:var(--editor-paper-bg);color:inherit}.worldbook-settings textarea{min-height:64px;resize:vertical}.worldbook-enabled{display:flex!important;align-items:center;gap:6px}.project-context-receipt{padding:8px;border-top:1px solid var(--dsw-alias-border-l1,ButtonBorder);font-size:12px}.proposal-card{display:grid;gap:8px}.proposal-card header,.proposal-card footer{display:flex;align-items:center;justify-content:space-between;gap:6px}.proposal-card pre{max-height:180px;overflow:auto;padding:8px;background:var(--dsw-alias-bg-l1,ButtonFace);white-space:pre-wrap}.warning{color:var(--dsw-alias-state-error,FireBrick)}.success{color:var(--dsw-alias-state-success,ForestGreen)}.pad{margin:0;padding:7px 10px;font-size:12px}
.workspace-checking{grid-column:1/-1;display:grid;place-content:center;gap:8px;padding:40px;text-align:center}.workspace-checking h1,.workspace-checking p{margin:0}.workspace-checking code{max-width:min(680px,80vw);overflow:hidden;color:var(--editor-paper-muted);text-overflow:ellipsis;white-space:nowrap}
.no-session{grid-template-columns:minmax(0,1fr);grid-template-rows:52px minmax(0,1fr);background:var(--editor-paper-inset)}.no-session .chrome{grid-column:1}.no-session .empty-paper{grid-column:1;grid-row:2;place-items:start center;overflow:auto;padding:clamp(40px,8vw,112px) 24px}.no-session .home-card{width:min(760px,100%);padding:clamp(32px,5vw,56px);border:1px solid var(--editor-paper-line);background:var(--editor-paper-bg);text-align:left}.no-session .home-card h1{font-size:clamp(34px,5vw,56px);margin-bottom:12px}.no-session .home-actions{justify-content:flex-start}.workspace-intent-prompt{display:grid;gap:8px;margin-top:16px;padding:14px;border:1px solid var(--editor-paper-line);border-radius:6px;background:var(--editor-paper-inset)}.workspace-intent-prompt p,.workspace-intent-prompt code{margin:0}.workspace-intent-prompt code{overflow:hidden;color:var(--editor-paper-muted);text-overflow:ellipsis;white-space:nowrap}.workspace-intent-prompt>div{display:flex;gap:7px;flex-wrap:wrap}.workspace-intent-prompt button{padding:7px 10px;border:1px solid var(--dsw-alias-border-l1,ButtonBorder);border-radius:4px;background:var(--editor-paper-bg);cursor:pointer}.home-recent{display:grid;gap:10px;margin-top:36px;padding-top:18px;border-top:1px solid var(--editor-paper-line)}.home-recent>header{display:flex;align-items:baseline;justify-content:space-between;gap:12px}.home-recent h2{margin:0;font-size:15px}.home-recent header small{color:var(--editor-paper-muted)}.workspace-list{display:grid;gap:6px}.workspace-row{position:relative;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:6px;padding:7px;border:1px solid var(--editor-paper-line);border-radius:5px;background:var(--editor-paper-bg)}.workspace-row .tree-row{display:grid;gap:3px;padding:4px}.workspace-row .tree-row small{overflow:hidden;color:var(--editor-paper-muted);font-size:11px;text-overflow:ellipsis;white-space:nowrap}.workspace-manage{align-self:start}.workspace-relocation{grid-column:1/-1;display:flex;align-items:center;gap:7px;flex-wrap:wrap;padding:8px;border-top:1px solid var(--editor-paper-line)}.workspace-relocation p,.workspace-relocation code{width:100%;margin:0}.workspace-relocation code{overflow:hidden;color:var(--editor-paper-muted);text-overflow:ellipsis;white-space:nowrap}.home-recent-empty{margin:0;padding:12px 0}
.layout-shell{grid-template-rows:52px minmax(0,1fr)}.layout-shell>.sidebar,.layout-shell>.editor,.layout-shell>.empty-paper,.layout-shell>.chat,.layout-shell>.panel-resizer{grid-column:auto;grid-row:2}.layout-shell.focus-mode{grid-template-columns:minmax(0,1fr)!important}.layout-shell.focus-mode .editor-header{justify-content:center}.layout-shell.focus-mode .editor-header>*:not(:first-child){display:none}.layout-shell.focus-mode .paper-input{width:min(920px,calc(100% - 48px));margin:20px 0}.layout-shell.focus-mode .editor-tools{justify-content:center}.layout-shell.focus-mode .editor-tools>span{display:none}
@media(max-width:1040px){.shell{grid-template-columns:220px minmax(0,1fr)}.layout-shell.assistant-open{grid-template-columns:220px minmax(0,1fr)!important}.layout-shell.assistant-open>.chat,.layout-shell.assistant-open>.panel-resizer.right{display:none}.assistant-launcher{display:flex}.workspace-chrome .project-switcher{max-width:220px}.topbar-actions>span{display:none}}
@media(max-width:760px){.shell{min-width:0}.chrome{gap:6px;padding:0 9px}.workspace-chrome{max-width:min(280px,58vw)}.workspace-chrome .project-switcher{max-width:180px}.layout-controls button{padding-inline:6px}.layout-controls button:nth-child(2){font-size:0}.layout-controls button:nth-child(2)::after{content:'专注';font-size:12px}.topbar-actions .settings-link{display:none}.layout-shell.files-open{grid-template-columns:minmax(0,1fr)!important}.layout-shell.files-open>.sidebar,.layout-shell.files-open>.panel-resizer.left{display:none}.editor-header{padding-inline:12px}.editor-header>span:last-child{display:none}.paper-input{padding:28px 22px;font-size:16px}.no-session .home-card{padding:28px 20px}.workspace-menu-panel{right:0;left:auto}}
@media(prefers-reduced-motion:reduce){.shell *{scroll-behavior:auto!important;transition:none!important;animation:none!important}}
`

/* Kept as empty exports so the root can continue to inject the historical
   style slots without reintroducing a competing visual system. */
export const homeStyles = ''
export const playfulStyles = ''
export const homePlayStyles = ''
